Ant d integration
balavishnuvj/all-in-one-repo pull request #6
Opened 2019-01-22 15:35 UTC by Indrawat04

2019-01-23 06:43 UTC, balavishnuvj commented
can you remove unwanted comments
also, add an example way to change the default theme.

2019-01-28 04:24 UTC, balavishnuvj requested changes

2019-01-28 04:24 UTC, balavishnuvj commented on src/routes/home/Home.js
> +export default compose(graphql(newsQuery))(Home);
do we need to compose, if it just `graphql`?

2019-01-28 04:24 UTC, balavishnuvj commented on tools/webpack.config.js
> +                'primary-color': '#1DA',
can you put these values in `theme.js` and import and spread it here. So that we need not modify webpack for theme changes.

2019-01-28 04:56 UTC, Indrawat04 commented on src/routes/home/Home.js
> +export default compose(graphql(newsQuery))(Home);
It happened because of auto-merge, I'll change it

2019-01-28 05:16 UTC, Indrawat04 commented on tools/webpack.config.js
> +                'primary-color': '#1DA',
Updated

2019-01-29 07:33 UTC, balavishnuvj approved these changes

2019-01-29 07:34 UTC, merged