header implemented with tsx, folder structure and styled components
balavishnuvj/all-in-one-repo pull request #7
Opened 2019-01-22 17:04 UTC by buddharajuprithvi

header implemented with

- tsx
- folder structure
- styled components

2019-01-23 02:43 UTC, balavishnuvj requested changes

2019-01-23 02:43 UTC, balavishnuvj commented on src/components/Header/__snapshots__/Header.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
the snapshot doesn't seem like a proper representation of the header components. Will ignore this for now and will update when we setup the test properly.

2019-01-23 02:43 UTC, balavishnuvj commented on src/components/Header/Header.tsx
> +  return (
destructure all the props at top, here `const {testingProps} = props`

2019-01-23 02:43 UTC, balavishnuvj commented on src/components/Header/Header.test.js
> +          context={{
context isn't an appropriate prop for the header. But will fix this later.

2019-01-23 02:43 UTC, balavishnuvj commented on src/components/Layout/Layout.js
> +          <Header testingProps="Sri Kanya" />
remove this change.

2019-01-23 02:43 UTC, balavishnuvj commented on src/d.ts
> +declare module '*.png' {
relocate this file to `src/@types/global.d.ts`

2019-01-23 02:43 UTC, balavishnuvj commented on src/components/Header/header.styled.ts
> +import styled from 'styled-components';
rename this file to `Header.styled.ts`, capital *H* for consistency.

2019-01-24 16:20 UTC, balavishnuvj requested changes

2019-01-24 16:20 UTC, balavishnuvj commented on package.json
> -    "@types/react-test-renderer": "^16.0.3",
why these changes?

2019-01-24 16:20 UTC, balavishnuvj commented on src/components/Header/header.styled.ts
> +import styled from 'styled-components';
file now changed

2019-01-24 16:20 UTC, balavishnuvj commented on src/components/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
> +    class="sc-bdVaJa kttCLS"
how come this changed when u didn't change the layout?

2019-01-24 16:20 UTC, balavishnuvj commented on yarn.lock
> -"@babel/runtime@^7.1.5":
why these changes?

2019-01-24 16:24 UTC, buddharajuprithvi commented on package.json
> -    "@types/react-test-renderer": "^16.0.3",
that came when I took a pull.

2019-01-24 16:27 UTC, buddharajuprithvi commented on src/components/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
> +    class="sc-bdVaJa kttCLS"
when I did yarn test -u
maybe then this much be updated

2019-01-24 16:55 UTC, balavishnuvj approved these changes

2019-01-24 16:55 UTC, merged